image: registry.gitlab.com/pages/hugo:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
  - tsc
  - mkdir .public
  - cp -r projects/* .public
  - mv .public public
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master
