image: registry.gitlab.com/pages/hugo:latest

stages:
  - build
  - deploy
services:
  - docker:dind

variables:
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  paths:
    - node_modules/

build:
  stage: build
  image: docker:stable
  script:
    - docker run -v $PWD:/ -w / node:latest npm install
    - docker run -v $PWD:/ -w / node:latest npm run-script build
  artifacts:
    paths:
    - static/dist/
  only:
    - master

pages:
  stage: deploy
  script:
  - cp -r projects/* public
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master
