stages:
  - build
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  paths:
    - projects/

build:
  stage: build
  image: node:latest
  script:
    - npm install
    - npm build
  artifacts:
    paths:
    - projects
  only:
    - master

pages:
  stage: deploy
  image: registry.gitlab.com/pages/hugo:latest
  dependencies:
  - build
  script:
  - mkdir public
  - cp -r projects/* public
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master
  before_script:
  - hugo version
