image: registry.gitlab.com/pages/hugo:latest

stages:
  - build
  - deploy
services:
  - docker:dind

variables:
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  paths:
    - node_modules/

build:
  stage: build
  image: docker:stable
  script:
    - docker run -v $PWD:/app -w /app node:10 npm install
    - docker run -v $PWD:/app -w /app node:10 npm run-script build
  artifacts:
    paths:
    - public
  only:
    - master

pages:
  stage: deploy
  dependencies:
  - build
  script:
  - cp -r projects/* public
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master
  before_script:
  - hugo version
