stages:
  - build
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  paths:
    - projects/

build:
  stage: build
  image: node:latest
  before_script:
    - git submodule add https://github.com/calintat/minimal.git themes/minimal
    - git submodule init
    - git submodule update
  script:
    - npm install
    - npm build
  artifacts:
    paths:
    - projects
  only:
    - master

pages:
  stage: deploy
  image: registry.gitlab.com/pages/hugo:latest
  dependencies:
  - build
  before_script:
  - hugo version
  script:
  - mkdir .public
  - cp -r * .public/
  - mv .public public
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master
